# https://github.com/uber-go/automaxprocs
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: gochatpass
      MYSQL_USER: gochatuser
      MYSQL_PASSWORD: gochatpass
      MYSQL_DATABASE: gochat
    ports:
      - "3306:3306"
    volumes:
      - "gochat_db:/var/lib/mysql"
volumes:
  gochat_db:

