name: Gochat Docker Image v1

on:
  push:
    branches: [ "v1" ]
  pull_request:
    branches: [ "v1" ]

permissions:
  packages: write
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repository
      uses: actions/checkout@v4
    - name: Registry login
      uses: docker/login-action@v3
      with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build the Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: ghcr.io/sprinter05/gochat:latest,ghcr.io/sprinter05/gochat:v1
