# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Gochat v1

on:
  push:
    branches: [ "v1" ]
  pull_request:
    branches: [ "v1" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'
    - name: Build all
      run: make all -j$(nproc)
    - name: Publish server
      uses: actions/upload-artifact@v4
      with:
        name: server
        path: build/gochat-server
    - name: Publish client
      uses: actions/upload-artifact@v4
      with:
        name: client
        path: build/gochat-client
